server:
  port: 8080
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  type:
#    aliases-package: com.likewater.mall.user.infrastructure.dal.mysql.dataobject
spring:
  shardingsphere:
    props: #是否打印解析的sql
      sql.show: true
    datasource:
      names: user0,user1 #不能使用下划线
      user0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/user0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        minimum-idle: 5       #连接池最小连接数
        maximum-pool-size: 50   #连接池最大连接数
        connection-timeout: 60000
        connection-test-query: SELECT 1
      user1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/user1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        minimum-idle: 5       #连接池最小连接数
        maximum-pool-size: 50   #连接池最大连接数
        connection-timeout: 60000
        connection-test-query: SELECT 1
    sharding:
      tables:
        user:
          actual-data-nodes: user${0..1}.user_${0..3}
          database-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user${id % 2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_${id % 4}