
server:
  port: 8081
mybatis:
  mapper-locations: classpath:/mapper/*.xml
#  type:
#    aliases-package: com.likewater.mall.user.infrastructure.dal.mysql.dataobject
spring:
  application:
    name: sharding-standard-strategy-example
  shardingsphere:
    props: #是否打印解析的sql
      sql.show: true
    datasource: #数据源配置
      names: db0,db1 #不能使用下划线
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/user0?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        minimum-idle: 5       #连接池最小连接数
        maximum-pool-size: 50   #连接池最大连接数
        connection-timeout: 60000
        connection-test-query: SELECT 1
      db1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3306/user1?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        minimum-idle: 5       #连接池最小连接数
        maximum-pool-size: 50   #连接池最大连接数
        connection-timeout: 60000
        connection-test-query: SELECT 1
    sharding:
      tables:
        user: #逻辑表名
          actual-data-nodes: db${0..1}.user_${0..3}
          database-strategy: #分库策略
            standard: #标识是标准分片策略
              sharding-column: id  #分片键
              precise-algorithm-class-name: com.example.sharding.standard.infrastructure.config.UserPreciseAlgorithmForDB #精确分片算法类名称，用于=和IN。
              range-algorithm-class-name: com.example.sharding.standard.infrastructure.config.UserRangeAlgorithmForDB #范围分片算法类名称，用于范围查询。

          table-strategy: #分表策略
            standard: #标识是标准分片策略
              sharding-column: id #分片键
              precise-algorithm-class-name: com.example.sharding.standard.infrastructure.config.UserPreciseAlgorithmForTable #精确分片算法类名称，用于=和IN。
              range-algorithm-class-name: com.example.sharding.standard.infrastructure.config.UserRangeAlgorithmForTable #范围分片算法类名称，用于范围查询。